### ISSUE TITLE
[Discuss] Current version leaks LOG macros from TLX, breaking other LOG macros uses

### ISSUE THREAD

**Issue by niklas88** [bingmann/stxxl#6]
We're using STXXL in the [QLever](https://github.com/ad-freiburg/qlever) SPARQL engine and as discussed with @bingmann I'm currently trying to upgrade to this STXXL fork.

Now QLever uses a custom `LOG` macro which is similar to but not compatible with the TLX `LOG` macro. Until now this didn't pose any problems with STXXL, however in the new version the `LOG` macro from TLX is included through the `stxxl/vector` header. This isn't strictly a bug as switching to use the same macro would fix this. I'm not sure however if it's a good idea to export such a generic non-namespaced name from a library.

**Comment by bingmann** [comment]
fixed with 91fa28088d1fec32952ff6427ef3a2943c5535c0
