### ISSUE TITLE
add_subdirectory() make with more parallelism than `make -j 1` breaks TLX header discovery

### ISSUE THREAD

**Issue by niklas88** [bingmann/stxxl#7]
So this is a weird one. In QLever we're using STXXL via `add_subdirectory()` and `target_link_libraries(foo … ${STXXL_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT})`. Somehow even with the old version we also needed

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${STXXL_CXX_FLAGS}")
    include_directories(SYSTEM ${STXXL_INCLUDE_DIRS})

However, if I then [switch](https://github.com/niklas88/QLever/tree/stxxl-update) to your version it can't find `tlx/define.hpp` needed in `stxxl/vector` like in [this build](https://travis-ci.org/niklas88/QLever/builds/410361863).

With just changing `make -j 3` in `.travis.yml` to `make -j 1` it then does find the includes like in [this build](https://travis-ci.org/niklas88/QLever/builds/410369812). This also doesn't seem to depend on the GCC version as it happens with GCC 8 on my workstation and Ubuntu 18.04's GCC in docker as well. That build breaks on a too old C++ standard and [after that](https://travis-ci.org/niklas88/QLever/builds/410376391) on issue #6 but at least that's easy to understand.

Note that any of the later changes also breaks with e.g. `make -j 3` again not finding `tlx/define.hpp`

**Comment by bingmann** [comment]
That is really weird, `tlx/define.hpp` is a simple file without any magic.
Can you run with `make VERBOSE=1`

**Comment by niklas88** [comment]
[This](https://travis-ci.org/niklas88/QLever/builds/410492371) is a build with the current version (that breaks on `LOG` with `make -j 1`)

**Comment by bingmann** [comment]
No idea. This should never occur.

**Comment by niklas88** [comment]
Ok, so after updating to the current version this same error occurs without parallelization as well. I tried adding `${TLX_INCLUDE_DIRS}` but that variable is empty. Also `${TLX_INSTALL_INCLUDE_DIR}` only contains `"include"`. To me this seems like there is something wrong with the cmake setup either on my or on your side.

This is the current build log:
https://travis-ci.org/niklas88/QLever/builds/436692004
and this is my branch for testing with the current STXXL
https://github.com/niklas88/QLever/tree/stxxl-update

Any idea what the problem could be?

**Comment by bingmann** [comment]
Yes, I used the new cmake features for include directories in tlx:
```cmake
  target_include_directories(tlx PUBLIC
    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/>
    $<INSTALL_INTERFACE:${TLX_INSTALL_INCLUDE_DIR}>)
```
This is supposed to add the includes when adding the library to the target_link_libraries set.
Apparently that not always works well.

Maybe you can try to change the line
```cmake
set(TLX_INCLUDE_DIRS "")
```
to
```cmake
set(TLX_INCLUDE_DIRS "${PROJECT_SOURCE_DIR}")
```

**Comment by niklas88** [comment]
Ok so I've got this working but I don't think it's right. I had to add

    set(TLX_INCLUDE_DIRS ${PROJECT_SOURCE_DIR}/ CACHE STRING "TLX Include Directories")

To the TLX CMakeLists.txt **and** also add

    include_directories(${STXXL_INCLUDE_DIRS})
    include_directories(${TLX_INCLUDE_DIRS})
    include_directories(${FOXXLL_INCLUDE_DIRS})

to my CMakeLists.txt. Normally I'd assume that only `include_directories(${STXXL_INCLUDE_DIRS})` is needed as only files in STXXL use TLX and FOXXLL.

**Comment by bingmann** [comment]
That's the reason cmake has these "target_include_directories" associated with targets.
And then one can have recursive targets and collect all their properties.

**Comment by niklas88** [comment]
Except it doesn't work in this case or are you saying I'm doing it wrong?

**Comment by niklas88** [comment]
So you think I would have to use `target_include_directories()` on STXXL for eache use of a STXXL thing instead of a global `include_directories(SYSTEM ${STXXL_INCLUDE_DIRS})`?

**Comment by bingmann** [comment]
This was a problem with QLever building sources without target dependencies:
https://github.com/niklas88/QLever/pull/1/commits/98bd5601813d1457a451ece82175e3286adfb586
